### ISSUE TITLE
SearchCondition 按照时间筛选没用不起效果! 什么情况

### ISSUE THREAD

**Issue by lhtuling** [andyedinborough/aenetmail#208]
var msgs = imap.Search(
                    SearchCondition.Undeleted().And(
                        SearchCondition.SentSince(new DateTime(2020, 1, 1)))
                  );

**Comment by robclayton** [comment]
If it's not obvious, this project is dead and has been for quite some time. If you haven't already, you should seriously consider switching over to [MailKit](https://github.com/jstedfast/MailKit) instead. You are wasting your time continuing to use this library.
