### ISSUE TITLE
Issue deleting Gmail messages

### ISSUE THREAD

**Issue by drittich** [andyedinborough/aenetmail#7]
When I use 

```
imap.DeleteMessage(message);
```

the message gets labeled as "Trash" but is still also labelled "Inbox" as well, so is not really deleted.

When I use 

```
imap.MoveMessage(message.Uid, "[Gmail]/Trash");
```

I get an exception of "1 EXPUNGE" thrown by method CheckResultOK

I am using commit d2062b542d925f1034d4ebef865143da8f7490fe (2011/11/28)

**Comment by Usama-7e** [comment]
jstedfast......hi i am working on "Email Management System" project in Flutter.................for getting emails,folders from Gmail i use Imap_Client Libarary.................i am gettting stuck now so please help me................As Backup for storing data i use sqlite database........
